Add a lockfile to avoid concurrent access
mendersoftware/grub-mender-grubenv pull request #28
Opened 2022-12-30 15:50 UTC by clementperon

Doing concurrent acces on mender grub environement utility will trig the following error:
/usr/bin/grub-editenv: error: invalid environment block.

This append when a process is editing an env so the other is trying to restore it.

Fix this by running critical section under a flock

Signed-off-by: Clément Péron <peron.clem@gmail.com>

2023-01-02 08:07 UTC, kacf requested changes
Thanks, looks like a good fix. A few small fixups:

* Make sure the author address matches the signoff address (this is why the CI is failing).

2023-01-02 13:43 UTC, clementperon commented on grub-mender-grubenv-print
> +LOCKFILE="/var/lock/fw_printenv.lock"
done

2023-01-02 13:44 UTC, clementperon commented
@kacf thanks i have fixed the commit author email.

Do you want me to add an entry in the Changelog ?

2023-01-02 13:52 UTC, kacf commented
No, you don't need to for this repository. I will add one once I update the SHA in meta-mender and mender-convert. The bot is just being a bit overeager (we will probably disable it for this repository).

2023-01-03 07:41 UTC, kacf approved these changes
Thanks!

2023-01-03 07:42 UTC, merged

2023-01-03 08:02 UTC, kacf commented
Changes applied in https://github.com/mendersoftware/meta-mender/pull/1879 and https://github.com/mendersoftware/mender-convert/pull/526.

2023-01-05 06:25 UTC, kacf commented
@clementperon: Looks like `sh` does not support the redirection syntax. Check out https://github.com/mendersoftware/grub-mender-grubenv/pull/29.